services:
  bot:
    build:
      dockerfile: Dockerfile
      context: .
  db:
    image: postgres:12.3-alpine
    env_file:
      - .env

    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
