services:
  bot:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - database_network
  db:
    image: postgres:12.3-alpine
    env_file:
      - .env
    networks:
      - database_network

    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  database_network:
    driver: bridge
